/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.ui;

import dk.sdu.mdsd.ui.AbstractArduinoDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ArduinoDSLUiModule extends AbstractArduinoDSLUiModule {
  public ArduinoDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
