/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mdsd.ArduinoDSLRuntimeModule;
import dk.sdu.mdsd.ArduinoDSLStandaloneSetup;
import dk.sdu.mdsd.ide.ArduinoDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ArduinoDSLIdeSetup extends ArduinoDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ArduinoDSLRuntimeModule _arduinoDSLRuntimeModule = new ArduinoDSLRuntimeModule();
    ArduinoDSLIdeModule _arduinoDSLIdeModule = new ArduinoDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_arduinoDSLRuntimeModule, _arduinoDSLIdeModule));
  }
}
