/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.ide;

import dk.sdu.mdsd.ide.AbstractArduinoDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ArduinoDSLIdeModule extends AbstractArduinoDSLIdeModule {
}
