/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLFactory
 * @model kind="package"
 * @generated
 */
public interface ArduinoDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "arduinoDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/mdsd/ArduinoDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "arduinoDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ArduinoDSLPackage eINSTANCE = dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ProgramImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Program</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__PROGRAM = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.RuleImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__BODY = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ConditionImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 2;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ExpressionImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpWeakOpImpl <em>Exp Weak Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ExpWeakOpImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExpWeakOp()
   * @generated
   */
  int EXP_WEAK_OP = 4;

  /**
   * The number of structural features of the '<em>Exp Weak Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_WEAK_OP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpStrongOpImpl <em>Exp Strong Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ExpStrongOpImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExpStrongOp()
   * @generated
   */
  int EXP_STRONG_OP = 5;

  /**
   * The number of structural features of the '<em>Exp Strong Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_STRONG_OP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ValueImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getValue()
   * @generated
   */
  int VALUE = 6;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.AttributeImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = VALUE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__COMPONENT = VALUE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.DeltaImpl <em>Delta</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.DeltaImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getDelta()
   * @generated
   */
  int DELTA = 8;

  /**
   * The number of structural features of the '<em>Delta</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELTA_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RuleBodyImpl <em>Rule Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.RuleBodyImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRuleBody()
   * @generated
   */
  int RULE_BODY = 9;

  /**
   * The feature id for the '<em><b>Assignment</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_BODY__ASSIGNMENT = 0;

  /**
   * The number of structural features of the '<em>Rule Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_BODY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.AssignmentImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 10;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.NodeImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getNode()
   * @generated
   */
  int NODE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ComponentImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ComponentBodyImpl <em>Component Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ComponentBodyImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getComponentBody()
   * @generated
   */
  int COMPONENT_BODY = 13;

  /**
   * The feature id for the '<em><b>Io</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY__IO = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY__TYPE = 1;

  /**
   * The feature id for the '<em><b>Pin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY__PIN = 2;

  /**
   * The feature id for the '<em><b>Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY__MAP = 3;

  /**
   * The feature id for the '<em><b>Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY__RATE = 4;

  /**
   * The feature id for the '<em><b>Smoothing</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY__SMOOTHING = 5;

  /**
   * The number of structural features of the '<em>Component Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_BODY_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.MapImpl <em>Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.MapImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getMap()
   * @generated
   */
  int MAP = 14;

  /**
   * The feature id for the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP__IN = 0;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP__OUT = 1;

  /**
   * The number of structural features of the '<em>Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.RangeImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRange()
   * @generated
   */
  int RANGE = 15;

  /**
   * The feature id for the '<em><b>Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__LOW = 0;

  /**
   * The feature id for the '<em><b>High</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__HIGH = 1;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RateImpl <em>Rate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.RateImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRate()
   * @generated
   */
  int RATE = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Rate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.SmoothingImpl <em>Smoothing</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.SmoothingImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getSmoothing()
   * @generated
   */
  int SMOOTHING = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMOOTHING__VALUE = 0;

  /**
   * The number of structural features of the '<em>Smoothing</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMOOTHING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpImpl <em>Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.ExpImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExp()
   * @generated
   */
  int EXP = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.FactorImpl <em>Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.FactorImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getFactor()
   * @generated
   */
  int FACTOR = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.PlusImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getPlus()
   * @generated
   */
  int PLUS = 20;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXP_WEAK_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.MinusImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getMinus()
   * @generated
   */
  int MINUS = 21;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXP_WEAK_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.MultImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getMult()
   * @generated
   */
  int MULT = 22;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXP_STRONG_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.arduinoDSL.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.arduinoDSL.impl.DivImpl
   * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getDiv()
   * @generated
   */
  int DIV = 23;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXP_STRONG_OP_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.arduinoDSL.Program#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Program</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Program#getProgram()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Program();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Rule#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Rule#getType()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Type();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Condition();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Rule#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Rule#getBody()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Body();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Condition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Condition#getLeft()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Left();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Condition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Condition#getOperator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Operator();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Condition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Condition#getRight()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.ExpWeakOp <em>Exp Weak Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Weak Op</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ExpWeakOp
   * @generated
   */
  EClass getExpWeakOp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.ExpStrongOp <em>Exp Strong Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Strong Op</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ExpStrongOp
   * @generated
   */
  EClass getExpStrongOp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.arduinoDSL.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Name();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.arduinoDSL.Attribute#getComponent <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Component</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Attribute#getComponent()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Component();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Delta <em>Delta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delta</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Delta
   * @generated
   */
  EClass getDelta();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.RuleBody <em>Rule Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Body</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.RuleBody
   * @generated
   */
  EClass getRuleBody();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.arduinoDSL.RuleBody#getAssignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assignment</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.RuleBody#getAssignment()
   * @see #getRuleBody()
   * @generated
   */
  EReference getRuleBody_Assignment();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Assignment#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Assignment#getAttribute()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Attribute();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Assignment#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Assignment#getValue()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.arduinoDSL.Node#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Node#getComponents()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Components();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Component#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Properties</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Component#getProperties()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Properties();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody <em>Component Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Body</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody
   * @generated
   */
  EClass getComponentBody();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getIo <em>Io</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Io</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody#getIo()
   * @see #getComponentBody()
   * @generated
   */
  EAttribute getComponentBody_Io();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody#getType()
   * @see #getComponentBody()
   * @generated
   */
  EAttribute getComponentBody_Type();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getPin <em>Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pin</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody#getPin()
   * @see #getComponentBody()
   * @generated
   */
  EAttribute getComponentBody_Pin();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getMap <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Map</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody#getMap()
   * @see #getComponentBody()
   * @generated
   */
  EReference getComponentBody_Map();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getRate <em>Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rate</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody#getRate()
   * @see #getComponentBody()
   * @generated
   */
  EReference getComponentBody_Rate();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getSmoothing <em>Smoothing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Smoothing</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.ComponentBody#getSmoothing()
   * @see #getComponentBody()
   * @generated
   */
  EReference getComponentBody_Smoothing();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Map <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Map
   * @generated
   */
  EClass getMap();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Map#getIn <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>In</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Map#getIn()
   * @see #getMap()
   * @generated
   */
  EReference getMap_In();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Map#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Out</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Map#getOut()
   * @see #getMap()
   * @generated
   */
  EReference getMap_Out();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Range#getLow <em>Low</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Low</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Range#getLow()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Low();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Range#getHigh <em>High</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>High</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Range#getHigh()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_High();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Rate <em>Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rate</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Rate
   * @generated
   */
  EClass getRate();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Rate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Rate#getValue()
   * @see #getRate()
   * @generated
   */
  EAttribute getRate_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Smoothing <em>Smoothing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Smoothing</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Smoothing
   * @generated
   */
  EClass getSmoothing();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.arduinoDSL.Smoothing#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Smoothing#getValue()
   * @see #getSmoothing()
   * @generated
   */
  EAttribute getSmoothing_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Exp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Exp
   * @generated
   */
  EClass getExp();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Exp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Exp#getLeft()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Exp#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Exp#getOperator()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Operator();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Exp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Exp#getRight()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Factor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Factor
   * @generated
   */
  EClass getFactor();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Factor#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Factor#getLeft()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Factor#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Factor#getOperator()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Operator();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.arduinoDSL.Factor#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Factor#getRight()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.arduinoDSL.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see dk.sdu.mdsd.arduinoDSL.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ArduinoDSLFactory getArduinoDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ProgramImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__PROGRAM = eINSTANCE.getProgram_Program();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.RuleImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__TYPE = eINSTANCE.getRule_Type();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__BODY = eINSTANCE.getRule_Body();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ConditionImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__LEFT = eINSTANCE.getCondition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__OPERATOR = eINSTANCE.getCondition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__RIGHT = eINSTANCE.getCondition_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ExpressionImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpWeakOpImpl <em>Exp Weak Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ExpWeakOpImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExpWeakOp()
     * @generated
     */
    EClass EXP_WEAK_OP = eINSTANCE.getExpWeakOp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpStrongOpImpl <em>Exp Strong Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ExpStrongOpImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExpStrongOp()
     * @generated
     */
    EClass EXP_STRONG_OP = eINSTANCE.getExpStrongOp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ValueImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.AttributeImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Component</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__COMPONENT = eINSTANCE.getAttribute_Component();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.DeltaImpl <em>Delta</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.DeltaImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getDelta()
     * @generated
     */
    EClass DELTA = eINSTANCE.getDelta();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RuleBodyImpl <em>Rule Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.RuleBodyImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRuleBody()
     * @generated
     */
    EClass RULE_BODY = eINSTANCE.getRuleBody();

    /**
     * The meta object literal for the '<em><b>Assignment</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_BODY__ASSIGNMENT = eINSTANCE.getRuleBody_Assignment();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.AssignmentImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__ATTRIBUTE = eINSTANCE.getAssignment_Attribute();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__VALUE = eINSTANCE.getAssignment_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.NodeImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__COMPONENTS = eINSTANCE.getNode_Components();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ComponentImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__PROPERTIES = eINSTANCE.getComponent_Properties();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ComponentBodyImpl <em>Component Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ComponentBodyImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getComponentBody()
     * @generated
     */
    EClass COMPONENT_BODY = eINSTANCE.getComponentBody();

    /**
     * The meta object literal for the '<em><b>Io</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_BODY__IO = eINSTANCE.getComponentBody_Io();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_BODY__TYPE = eINSTANCE.getComponentBody_Type();

    /**
     * The meta object literal for the '<em><b>Pin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_BODY__PIN = eINSTANCE.getComponentBody_Pin();

    /**
     * The meta object literal for the '<em><b>Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_BODY__MAP = eINSTANCE.getComponentBody_Map();

    /**
     * The meta object literal for the '<em><b>Rate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_BODY__RATE = eINSTANCE.getComponentBody_Rate();

    /**
     * The meta object literal for the '<em><b>Smoothing</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_BODY__SMOOTHING = eINSTANCE.getComponentBody_Smoothing();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.MapImpl <em>Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.MapImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getMap()
     * @generated
     */
    EClass MAP = eINSTANCE.getMap();

    /**
     * The meta object literal for the '<em><b>In</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP__IN = eINSTANCE.getMap_In();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP__OUT = eINSTANCE.getMap_Out();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.RangeImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>Low</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__LOW = eINSTANCE.getRange_Low();

    /**
     * The meta object literal for the '<em><b>High</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__HIGH = eINSTANCE.getRange_High();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.RateImpl <em>Rate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.RateImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getRate()
     * @generated
     */
    EClass RATE = eINSTANCE.getRate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RATE__VALUE = eINSTANCE.getRate_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.SmoothingImpl <em>Smoothing</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.SmoothingImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getSmoothing()
     * @generated
     */
    EClass SMOOTHING = eINSTANCE.getSmoothing();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMOOTHING__VALUE = eINSTANCE.getSmoothing_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.ExpImpl <em>Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.ExpImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getExp()
     * @generated
     */
    EClass EXP = eINSTANCE.getExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__LEFT = eINSTANCE.getExp_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__OPERATOR = eINSTANCE.getExp_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__RIGHT = eINSTANCE.getExp_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.FactorImpl <em>Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.FactorImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getFactor()
     * @generated
     */
    EClass FACTOR = eINSTANCE.getFactor();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__LEFT = eINSTANCE.getFactor_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__OPERATOR = eINSTANCE.getFactor_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__RIGHT = eINSTANCE.getFactor_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.PlusImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.MinusImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.MultImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.arduinoDSL.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.arduinoDSL.impl.DivImpl
     * @see dk.sdu.mdsd.arduinoDSL.impl.ArduinoDSLPackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

  }

} //ArduinoDSLPackage
