/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getIo <em>Io</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getType <em>Type</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getPin <em>Pin</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getMap <em>Map</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getRate <em>Rate</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getSmoothing <em>Smoothing</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody()
 * @model
 * @generated
 */
public interface ComponentBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Io</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Io</em>' attribute.
   * @see #setIo(String)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody_Io()
   * @model
   * @generated
   */
  String getIo();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getIo <em>Io</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Io</em>' attribute.
   * @see #getIo()
   * @generated
   */
  void setIo(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Pin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pin</em>' attribute.
   * @see #setPin(int)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody_Pin()
   * @model
   * @generated
   */
  int getPin();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getPin <em>Pin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pin</em>' attribute.
   * @see #getPin()
   * @generated
   */
  void setPin(int value);

  /**
   * Returns the value of the '<em><b>Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map</em>' containment reference.
   * @see #setMap(Map)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody_Map()
   * @model containment="true"
   * @generated
   */
  Map getMap();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getMap <em>Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map</em>' containment reference.
   * @see #getMap()
   * @generated
   */
  void setMap(Map value);

  /**
   * Returns the value of the '<em><b>Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rate</em>' containment reference.
   * @see #setRate(Rate)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody_Rate()
   * @model containment="true"
   * @generated
   */
  Rate getRate();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getRate <em>Rate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rate</em>' containment reference.
   * @see #getRate()
   * @generated
   */
  void setRate(Rate value);

  /**
   * Returns the value of the '<em><b>Smoothing</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smoothing</em>' containment reference.
   * @see #setSmoothing(Smoothing)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getComponentBody_Smoothing()
   * @model containment="true"
   * @generated
   */
  Smoothing getSmoothing();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.ComponentBody#getSmoothing <em>Smoothing</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Smoothing</em>' containment reference.
   * @see #getSmoothing()
   * @generated
   */
  void setSmoothing(Smoothing value);

} // ComponentBody
