/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delta</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getDelta()
 * @model
 * @generated
 */
public interface Delta extends Value
{
} // Delta
