/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Map#getIn <em>In</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Map#getOut <em>Out</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getMap()
 * @model
 * @generated
 */
public interface Map extends EObject
{
  /**
   * Returns the value of the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' containment reference.
   * @see #setIn(Range)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getMap_In()
   * @model containment="true"
   * @generated
   */
  Range getIn();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Map#getIn <em>In</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' containment reference.
   * @see #getIn()
   * @generated
   */
  void setIn(Range value);

  /**
   * Returns the value of the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' containment reference.
   * @see #setOut(Range)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getMap_Out()
   * @model containment="true"
   * @generated
   */
  Range getOut();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Map#getOut <em>Out</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out</em>' containment reference.
   * @see #getOut()
   * @generated
   */
  void setOut(Range value);

} // Map
