/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getMinus()
 * @model
 * @generated
 */
public interface Minus extends ExpWeakOp
{
} // Minus
