/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends ExpStrongOp
{
} // Mult
