/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.NumberLiteral#getFloat <em>Float</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.NumberLiteral#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getNumberLiteral()
 * @model
 * @generated
 */
public interface NumberLiteral extends Value
{
  /**
   * Returns the value of the '<em><b>Float</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float</em>' attribute.
   * @see #setFloat(String)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getNumberLiteral_Float()
   * @model
   * @generated
   */
  String getFloat();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.NumberLiteral#getFloat <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float</em>' attribute.
   * @see #getFloat()
   * @generated
   */
  void setFloat(String value);

  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getNumberLiteral_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.NumberLiteral#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // NumberLiteral
