/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Range#getLow <em>Low</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Range#getHigh <em>High</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
  /**
   * Returns the value of the '<em><b>Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Low</em>' attribute.
   * @see #setLow(float)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRange_Low()
   * @model
   * @generated
   */
  float getLow();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Range#getLow <em>Low</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Low</em>' attribute.
   * @see #getLow()
   * @generated
   */
  void setLow(float value);

  /**
   * Returns the value of the '<em><b>High</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>High</em>' attribute.
   * @see #setHigh(float)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRange_High()
   * @model
   * @generated
   */
  float getHigh();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Range#getHigh <em>High</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>High</em>' attribute.
   * @see #getHigh()
   * @generated
   */
  void setHigh(float value);

} // Range
