/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.RuleBody#getAssignment <em>Assignment</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRuleBody()
 * @model
 * @generated
 */
public interface RuleBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mdsd.arduinoDSL.Assignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference list.
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRuleBody_Assignment()
   * @model containment="true"
   * @generated
   */
  EList<Assignment> getAssignment();

} // RuleBody
