/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.arduinoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Rule#getType <em>Type</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link dk.sdu.mdsd.arduinoDSL.Rule#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRule_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Rule#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRule_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Rule#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(RuleBody)
   * @see dk.sdu.mdsd.arduinoDSL.ArduinoDSLPackage#getRule_Body()
   * @model containment="true"
   * @generated
   */
  RuleBody getBody();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.arduinoDSL.Rule#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(RuleBody value);

} // Rule
