/*
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mdsd.parser.antlr.internal.InternalArduinoDSLParser;
import dk.sdu.mdsd.services.ArduinoDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ArduinoDSLParser extends AbstractAntlrParser {

	@Inject
	private ArduinoDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArduinoDSLParser createParser(XtextTokenStream stream) {
		return new InternalArduinoDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ArduinoDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArduinoDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
