/*
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mdsd.arduino.ui.internal.ArduinoActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ArduinoDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ArduinoActivator.getInstance().getInjector("dk.sdu.mdsd.ArduinoDSL");
	}

}
