/*
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.ui;

import com.google.inject.Injector;
import dk.sdu.mdsd.arduino.ui.internal.ArduinoActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArduinoDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ArduinoActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ArduinoActivator activator = ArduinoActivator.getInstance();
		return activator != null ? activator.getInjector(ArduinoActivator.DK_SDU_MDSD_ARDUINODSL) : null;
	}

}
