/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.ui.contentassist;

import dk.sdu.mdsd.ui.contentassist.AbstractArduinoDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ArduinoDSLProposalProvider extends AbstractArduinoDSLProposalProvider {
}
