/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd.validation;

import dk.sdu.mdsd.validation.AbstractArduinoDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ArduinoDSLValidator extends AbstractArduinoDSLValidator {
}
