/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd;

import dk.sdu.mdsd.ArduinoDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ArduinoDSLStandaloneSetup extends ArduinoDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new ArduinoDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
