/**
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd;

import dk.sdu.mdsd.AbstractArduinoDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ArduinoDSLRuntimeModule extends AbstractArduinoDSLRuntimeModule {
}
