/*
 * generated by Xtext 2.17.0
 */
package dk.sdu.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArduinoDSLStandaloneSetup extends ArduinoDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ArduinoDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
